name: Sync README to Notion

on:
  push:
    branches:
      - main  # Если у вас ветка называется master, замените main на master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push README to Notion
        uses: cvscarlos/markdown-to-notion-action@v1.0.4
        with:
          # По документации этого плагина параметры пишутся так:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_page_id: ${{ secrets.NOTION_PAGE_ID }}
          markdown_file_path: './README.md'